pretrained_model_path: models/StableDiffusion/stable-diffusion-v1-5
motion_module: models/Motion_Module/mm_sd_v14.ckpt
motion_module_pe_multiplier: 1
output_dir: models/Motion_Module/webvid-val-5k-finetune-sd14
train_data:
  meta_video_root: /mnt/public02/dataset/video_language_datasets/wanghaofan/webvid/results_2M_val
  meta_path: data/webvid-5k.json
  n_sample_frames: 16
  width: 256
  height: 256
  sample_start_idx: 0
  sample_frame_rate: 16
validation_data:
  prompts:
  - a woman standing on the side of a road at night,girl, long hair, motor vehicle, car, looking at viewer, ground vehicle, night, hands in pockets, blurry background, coat, black hair, parted lips, bokeh, jacket, brown hair, outdoors, red lips, upper body, artist name
  video_length: 16
  width: 256
  height: 256
  temporal_context: 16
  strides: 3
  overlap: 4
  num_inference_steps: 20
  guidance_scale: 12.5
  use_inv_latent: false
  num_inv_steps: 50
learning_rate: 1.0e-05
train_batch_size: 8
max_train_steps: 20000
checkpointing_steps: 2500
validation_steps: 2500
train_whole_module: true
seed: 33
mixed_precision: fp16
use_8bit_adam: false
gradient_checkpointing: true
enable_xformers_memory_efficient_attention: true